; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.26"

projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.2"

projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc4"

projects[admin_theme][subdir] = "contrib"
projects[admin_theme][version] = "1.0"

projects[auto_entitylabel][subdir] = "contrib"
projects[auto_entitylabel][version] = "1.2+4-dev"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.4"

projects[cas][version] = "1.2"
projects[cas][patches][] = "http://drupal.org/files/1394666-cas_library_path-5.patch"

projects[cas_attributes][version] = "1.0-rc2"

projects[cer][subdir] = "contrib"
projects[cer][version] = "2.x-dev"

projects[chosen][subdir] = "contrib"
projects[chosen][version] = "2.0-alpha4"

projects[ckeditor][subdir] = "contrib"
projects[ckeditor][version] = "1.13"

projects[computed_field][subdir] = "contrib"
projects[computed_field][version] = "1.0"

projects[conditional_fields][subdir] = "contrib"
projects[conditional_fields][version] = "3.0-alpha1"

projects[context][subdir] = "contrib"
projects[context][version] = "3.2"

projects[date][subdir] = "contrib"
projects[date][version] = "2.7"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[ds][subdir] = "contrib"
projects[ds][version] = "2.6"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.3"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.1"

projects[features_extra][subdir] = "contrib"
projects[features_extra][version] = "1.0-beta1"

projects[features][subdir] = "contrib"
projects[features][version] = "2.0"

projects[feeds][subdir] = "contrib"
projects[feeds][version] = "2.0-alpha8"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.3"

projects[field_permissions][subdir] = "contrib"
projects[field_permissions][version] = "1.0-beta2"

projects[fillpdf][subdir] = "contrib"
projects[fillpdf][version] = "1.9"

projects[flag][subdir] = "contrib"
projects[flag][version] = "3.3"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.4"

projects[inline_entity_form][subdir] = "contrib"
projects[inline_entity_form][version] = "1.5+1-dev"

projects[job_scheduler][subdir] = "contrib"
projects[job_scheduler][version] = "2.0-alpha3"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.3"

projects[location][subdir] = "contrib"
projects[ldap][version] = "1.0-beta12"

projects[link][subdir] = "contrib"
projects[link][version] = "1.2"

projects[location][subdir] = "contrib"
projects[location][version] = "3.1"

projects[maillog][subdir] = "contrib"
projects[maillog][version] = "1.x-dev"

projects[menu_attributes][subdir] = "contrib"
projects[menu_attributes][version] = "1.0-rc2"

projects[menu_trail_by_path][subdir] = "contrib"
projects[menu_trail_by_path][version] = "2.0"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "1.8"

projects[page_title][subdir] = "contrib"
projects[page_title][version] = "2.7"

projects[panels_breadcrumbs][subdir] = "contrib"
projects[panels_breadcrumbs][version] = "2.1"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[pathologic][subdir] = "contrib"
projects[pathologic][version] = "2.12"

projects[poormanscron][subdir] = "contrib"
projects[poormanscron][version] = "2.x-dev"

projects[rules][subdir] = "contrib"
projects[rules][version] = "2.6+1-dev"

projects[rules_conditional][subdir] = "contrib"
projects[rules_conditional][version] = "1.0-beta2"

projects[rules_forms][subdir] = "contrib"
projects[rules_forms][version] = "1.0-rc2"

projects[schemaorg][subdir] = "contrib"
projects[schemaorg][version] = "1.0-beta4"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[tablefield][subdir] = "contrib"
projects[tablefield][version] = "2.2"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[total_control][subdir] = "contrib"
projects[total_control][version] = "2.4"

projects[uuid][subdir] = "contrib"
projects[uuid][version] = "1.0-alpha5"

projects[uuid_features][subdir] = "contrib"
projects[uuid_features][version] = "1.0-alpha4"

projects[views][subdir] = "contrib"
projects[views][version] = "3.7"

; Themes
projects[omega][subdir] = "contrib"
projects[omega][version] = "3.1"

projects[rubik][subdir] = "contrib"
projects[rubik][version] = "4.0-rc1"

projects[skeletontheme][subdir] = "contrib"
projects[skeletontheme][version] = "1.3"

projects[tao][subdir] = "contrib"
projects[tao][version] = "3.0-beta4"
