; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.26"

; Modules
projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.4"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.4"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.3"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.3"

projects[save_draft][subdir] = "contrib"
projects[save_draft][version] = "1.4"

; Themes
projects[omega][subdir] = "contrib"
projects[omega][version] = "3.1"

projects[skeletontheme][subdir] = "contrib"
projects[skeletontheme][version] = "1.3"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[tests][download][type] = ""
projects[tests][download][url] = ""
projects[tests][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[pantheon_apachesolr][download][type] = ""
projects[pantheon_apachesolr][download][url] = ""
projects[pantheon_apachesolr][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[pantheon_api][download][type] = ""
projects[pantheon_api][download][url] = ""
projects[pantheon_api][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[pantheon_login][download][type] = ""
projects[pantheon_login][download][url] = ""
projects[pantheon_login][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[psr_0_test][download][type] = ""
projects[psr_0_test][download][url] = ""
projects[psr_0_test][type] = "module"

