<?php
/**
 * @file
 * staff_job.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function staff_job_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-job_staff-field_staff_job_appreq'
  $field_instances['node-job_staff-field_staff_job_appreq'] = array(
    'bundle' => 'job_staff',
    'default_value' => array(
      0 => array(
        'value' => 'Default text goes here.',
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 16,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_staff_job_appreq',
    'label' => 'Application Instructions',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 13,
    ),
  );

  // Exported field_instance: 'node-job_staff-field_staff_job_benefits'
  $field_instances['node-job_staff-field_staff_job_benefits'] = array(
    'bundle' => 'job_staff',
    'default_value' => array(
      0 => array(
        'value' => 'Default text goes here.',
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 17,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_staff_job_benefits',
    'label' => 'Benefits',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 12,
    ),
  );

  // Exported field_instance: 'node-job_staff-field_staff_job_criminalcheck'
  $field_instances['node-job_staff-field_staff_job_criminalcheck'] = array(
    'bundle' => 'job_staff',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => 'Is a criminal background check required?',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 13,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_staff_job_criminalcheck',
    'label' => 'Criminal Background Check',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 0,
      ),
      'type' => 'options_onoff',
      'weight' => 14,
    ),
  );

  // Exported field_instance: 'node-job_staff-field_staff_job_department'
  $field_instances['node-job_staff-field_staff_job_department'] = array(
    'bundle' => 'job_staff',
    'default_value' => array(
      0 => array(
        'value' => 'Default text goes here.',
      ),
    ),
    'deleted' => 0,
    'description' => 'The department for this job.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 5,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_staff_job_department',
    'label' => 'Department',
    'required' => 1,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 5,
    ),
  );

  // Exported field_instance: 'node-job_staff-field_staff_job_depoverview'
  $field_instances['node-job_staff-field_staff_job_depoverview'] = array(
    'bundle' => 'job_staff',
    'default_value' => array(
      0 => array(
        'value' => 'Default text goes here.',
      ),
    ),
    'deleted' => 0,
    'description' => 'An overview of the department for this job.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 7,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_staff_job_depoverview',
    'label' => 'Departmental Overview',
    'required' => 1,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 7,
    ),
  );

  // Exported field_instance: 'node-job_staff-field_staff_job_fullorpart'
  $field_instances['node-job_staff-field_staff_job_fullorpart'] = array(
    'bundle' => 'job_staff',
    'default_value' => array(
      0 => array(
        'value' => 1,
      ),
    ),
    'deleted' => 0,
    'description' => 'Is this job full or part time?',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 3,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_staff_job_fullorpart',
    'label' => 'Full or Part Time',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => 3,
    ),
  );

  // Exported field_instance: 'node-job_staff-field_staff_job_id'
  $field_instances['node-job_staff-field_staff_job_id'] = array(
    'bundle' => 'job_staff',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 15,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_staff_job_id',
    'label' => 'Job#',
    'required' => FALSE,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'node-job_staff-field_staff_job_location'
  $field_instances['node-job_staff-field_staff_job_location'] = array(
    'bundle' => 'job_staff',
    'default_value' => array(
      0 => array(
        'value' => 'Default text goes here.',
      ),
    ),
    'deleted' => 0,
    'description' => 'The location of this job.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_staff_job_location',
    'label' => 'Location',
    'required' => 1,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'node-job_staff-field_staff_job_notes'
  $field_instances['node-job_staff-field_staff_job_notes'] = array(
    'bundle' => 'job_staff',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Got any special notes about this job to add?',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 14,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_staff_job_notes',
    'label' => 'Special Notes',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 15,
    ),
  );

  // Exported field_instance: 'node-job_staff-field_staff_job_qpreferred'
  $field_instances['node-job_staff-field_staff_job_qpreferred'] = array(
    'bundle' => 'job_staff',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'An overview of the preferred qualifications for this job.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 10,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_staff_job_qpreferred',
    'label' => 'Preferred Qualifications',
    'required' => 1,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 10,
    ),
  );

  // Exported field_instance: 'node-job_staff-field_staff_job_qrequired'
  $field_instances['node-job_staff-field_staff_job_qrequired'] = array(
    'bundle' => 'job_staff',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'An overview of the required qualifications for this job.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 9,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_staff_job_qrequired',
    'label' => 'Required Qualifications',
    'required' => 1,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 9,
    ),
  );

  // Exported field_instance: 'node-job_staff-field_staff_job_regortemp'
  $field_instances['node-job_staff-field_staff_job_regortemp'] = array(
    'bundle' => 'job_staff',
    'default_value' => array(
      0 => array(
        'value' => 1,
      ),
    ),
    'deleted' => 0,
    'description' => 'Is this job regular or temporary?',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 4,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_staff_job_regortemp',
    'label' => 'Regular or Temporary',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => 4,
    ),
  );

  // Exported field_instance: 'node-job_staff-field_staff_job_responsibilities'
  $field_instances['node-job_staff-field_staff_job_responsibilities'] = array(
    'bundle' => 'job_staff',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'An overview of the responsibilities this job will require.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 8,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_staff_job_responsibilities',
    'label' => 'Responsibilities',
    'required' => 1,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 8,
    ),
  );

  // Exported field_instance: 'node-job_staff-field_staff_job_reviewdate'
  $field_instances['node-job_staff-field_staff_job_reviewdate'] = array(
    'bundle' => 'job_staff',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'The application review date for this job.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 6,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_staff_job_reviewdate',
    'label' => 'Application Review Date',
    'required' => 1,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 6,
    ),
  );

  // Exported field_instance: 'node-job_staff-field_staff_job_salary'
  $field_instances['node-job_staff-field_staff_job_salary'] = array(
    'bundle' => 'job_staff',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 18,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_staff_job_salary',
    'label' => 'Salary',
    'required' => FALSE,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 11,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('An overview of the department for this job.');
  t('An overview of the preferred qualifications for this job.');
  t('An overview of the required qualifications for this job.');
  t('An overview of the responsibilities this job will require.');
  t('Application Instructions');
  t('Application Review Date');
  t('Benefits');
  t('Criminal Background Check');
  t('Department');
  t('Departmental Overview');
  t('Full or Part Time');
  t('Got any special notes about this job to add?');
  t('Is a criminal background check required?');
  t('Is this job full or part time?');
  t('Is this job regular or temporary?');
  t('Job#');
  t('Location');
  t('Preferred Qualifications');
  t('Regular or Temporary');
  t('Required Qualifications');
  t('Responsibilities');
  t('Salary');
  t('Special Notes');
  t('The application review date for this job.');
  t('The department for this job.');
  t('The location of this job.');

  return $field_instances;
}
